name: "CTF Challenges YAML Linter"
description: "Lint challenge.yml files for ctfcli with comprehensive validation rules"
author: "diver-osint-ctf"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  repository:
    description: "Repository name (owner/repo)"
    required: false
    default: ${{ github.repository }}

  pr-number:
    description: "Pull request number"
    required: false
    default: ${{ github.event.number }}

outputs:
  result:
    description: "Linting result (success/failure)"
    value: ${{ steps.lint.outputs.result }}

  errors-found:
    description: "Whether any errors were found"
    value: ${{ steps.lint.outputs.errors-found }}

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Download dependencies
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        go mod download

    - name: Build linter
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        go build -o clilint .

    - name: Run linter
      id: lint
      shell: bash
      env:
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_PR_NUMBER: ${{ inputs.pr-number }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        cd "${{ github.action_path }}"

        # Copy linter to workspace for execution
        cp clilint "${{ github.workspace }}/clilint"
        cd "${{ github.workspace }}"

        echo "Running: ./clilint --comment-pr"

        # Run linter and capture exit code
        if ./clilint --comment-pr; then
          echo "result=success" >> $GITHUB_OUTPUT
          echo "errors-found=false" >> $GITHUB_OUTPUT
          echo "✅ All linting checks passed successfully!"
          exit 0
        else
          echo "result=failure" >> $GITHUB_OUTPUT  
          echo "errors-found=true" >> $GITHUB_OUTPUT
          echo "❌ Linting failed. Please fix the issues above."
          exit 1
        fi
